management:
endpoints:
web:
  exposure:
    include: "*"
 
spring: 
jpa: 
properties: 
  hibernate: 
    dialect: org.hibernate.dialect.MySQL5Dialect
hibernate: 
  ddl-auto: update
 
greeting: Hello
---
spring: 
profiles: dev
greeting: Hola
---
spring: 
profiles: prod
greeting: Hallo
