management:
endpoints:
web:
  exposure:
    include: "*"
 
spring: 
jpa: 
properties: 
  hibernate: 
    dialect: org.hibernate.dialect.MySQL5Dialect
hibernate: 
  ddl-auto: update
 
greetingLanguage: Hello
---
spring: 
profiles: dev
greetingLanguage: Hola
---
spring: 
profiles: prod
greetingLanguage: Hallo
